name: Deploy Components to Mainnet
on:
  push:
    branches: [main]
jobs:
  deploy-mainnet:
    uses: FroVolod/bos-cli-rs/.github/workflows/deploy-mainnet.yml@master
    with:
      deploy-account-address: bos.proofofvibes.near
      signer-account-address: bos.proofofvibes.near
      signer-public-key: ed25519:DucJdnMcR4qoWv5xZSgwfcXeC8x3ZdBCyhRMsmAigU8K
    secrets:
      SIGNER_PRIVATE_KEY: ed25519:4u2CfbYLNHpi2DtsvE954miPpuX1oTTXkCNTu628nnRPiW5E9UijcJoKRPBPUhrnwEtPdQuhvFKm7vhmFzqzzrmh
