name: Deploy Components to Mainnet
on:
  push:
    branches: [main]
jobs:
  deploy-mainnet:
    uses: FroVolod/bos-cli-rs/.github/workflows/deploy-mainnet.yml@master
    with:
      deploy-account-address:  ${{ inputs.deploy-account-address }}
      signer-account-address: ${{ inputs.signer-account-address }}
      signer-public-key: ${{ inputs.signer-public-key }}
    secrets:
      SIGNER_PRIVATE_KEY:  ${{ secrets.SIGNER_PRIVATE_KEY }}
